const PRODUCT_IMAGES = {
  // Original Luxury Items
  prod_lv_neverfull: '/assets/images/products/lv-neverfull.png',
  prod_dior_lady: '/assets/images/products/dior-lady.png',
  prod_chanel_flap: '/assets/images/products/chanel-flap.png',
  prod_hermes_birkin: '/assets/images/products/hermes-birkin.png',
  prod_rolex_submariner: '/assets/images/products/rolex-submariner.png',
  prod_rolex_datejust: '/assets/images/products/rolex-datejust.png',
  prod_cartier_tank: '/assets/images/products/cartier-tank.png',
  prod_apm_meteorites: '/assets/images/products/apm-meteorites.png',
  prod_cartier_love: '/assets/images/products/cartier-love.png',
  prod_vca_alhambra: '/assets/images/products/vca-alhambra.png',
  prod_tiffany_smile: '/assets/images/products/tiffany-smile.png',
  prod_bvlgari_bzero1: '/assets/images/products/bvlgari-bzero1.png',

  // First Expansion
  prod_bottega_jodie: '/assets/images/products/bottega-jodie.png',
  prod_ysl_kate: '/assets/images/products/ysl-kate.png',
  prod_celine_triomphe: '/assets/images/products/celine-triomphe.png',
  prod_prada_cleo: '/assets/images/products/prada-cleo.png',
  prod_gucci_jackie: '/assets/images/products/gucci-jackie.png',
  prod_loewe_puzzle: '/assets/images/products/loewe-puzzle.png',
  prod_omega_speedmaster: '/assets/images/products/omega-speedmaster.png',
  prod_patek_nautilus: '/assets/images/products/patek-nautilus.png',
  prod_ap_royaloak: '/assets/images/products/ap-royaloak.png',
  prod_cartier_santos: '/assets/images/products/cartier-santos.png',
  prod_tudor_blackbay: '/assets/images/products/tudor-blackbay.png',
  prod_iwc_portugieser: '/assets/images/products/iwc-portugieser.png',
  prod_cartier_juste: '/assets/images/products/cartier-juste.png',
  prod_bvlgari_serpenti: '/assets/images/products/bvlgari-serpenti.png',
  prod_tiffany_lock: '/assets/images/products/tiffany-lock.png',
  prod_chaumet_bee: '/assets/images/products/chaumet-bee.png',
  prod_messika_move: '/assets/images/products/messika-move.png',
  prod_chopard_ice: '/assets/images/products/chopard-ice.png',
  prod_vca_sweet: '/assets/images/products/vca-sweet.png',
  prod_tiffany_hardwear: '/assets/images/products/tiffany-hardwear.png',
  prod_bvlgari_divas: '/assets/images/products/bvlgari-divas.png',
  prod_cartier_trinity: '/assets/images/products/cartier-trinity.png',
  prod_piaget_possession: '/assets/images/products/piaget-possession.png',
  prod_messika_baby: '/assets/images/products/messika-baby.png',

  // Second Expansion
  prod_celine_belt: '/assets/images/products/celine-belt.png',
  prod_gucci_dionysus: '/assets/images/products/gucci-dionysus.png',
  prod_fendi_baguette: '/assets/images/products/fendi-baguette.png',
  prod_chloe_woody: '/assets/images/products/chloe-woody.png',
  prod_balenciaga_hourglass: '/assets/images/products/balenciaga-hourglass.png',
  prod_valentino_rockstud: '/assets/images/products/valentino-rockstud.png',
  prod_givenchy_antigona: '/assets/images/products/givenchy-antigona.png',
  prod_salvatore_studio: '/assets/images/products/salvatore-studio.png',
  prod_burberry_lola: '/assets/images/products/burberry-lola.png',
  prod_mulberry_bayswater: '/assets/images/products/mulberry-bayswater.png',
  prod_jacquemus_chiquito: '/assets/images/products/jacquemus-chiquito.png',
  prod_alexander_mcqueen_skull: '/assets/images/products/alexander-mcqueen-skull.png',
  prod_staud_moon: '/assets/images/products/staud-moon.png',
  prod_mansur_gavriel_bucket: '/assets/images/products/mansur-gavriel-bucket.png',
  prod_proenza_ps1: '/assets/images/products/proenza-ps1.png',
  prod_tag_heuer_monaco: '/assets/images/products/tag-heuer-monaco.png',
  prod_breitling_navitimer: '/assets/images/products/breitling-navitimer.png',
  prod_grand_seiko_snowflake: '/assets/images/products/grand-seiko-snowflake.png',
  prod_panerai_luminor: '/assets/images/products/panerai-luminor.png',
  prod_zenith_el_primero: '/assets/images/products/zenith-el_primero.png',
  prod_jaeger_lecoultre_reverso: '/assets/images/products/jaeger-lecoultre-reverso.png',
  prod_hublot_bigbang: '/assets/images/products/hublot-bigbang.png',
  prod_longines_spirit: '/assets/images/products/longines-spirit.png',
  prod_tissot_prx: '/assets/images/products/tissot-prx.png',
  prod_oris_diver: '/assets/images/products/oris-diver.png',
  prod_hamilton_murph: '/assets/images/products/hamilton-murph.png',
  prod_seiko_prospex: '/assets/images/products/seiko-prospex.png',
  prod_baume_mercier_clifton: '/assets/images/products/baume-mercier-clifton.png',
  prod_rado_captain: '/assets/images/products/rado-captain.png',
  prod_nomos_tangente: '/assets/images/products/nomos-tangente.png',
  prod_david_yurman_cable: '/assets/images/products/david-yurman-cable.png',
  prod_john_hardy_legends: '/assets/images/products/john-hardy-legends.png',
  prod_roberto_coin_romano: '/assets/images/products/roberto-coin-romano.png',
  prod_pomellato_nudo: '/assets/images/products/pomellato-nudo.png',
  prod_buccellati_opera: '/assets/images/products/buccellati-opera.png',
  prod_stephen_webster_ray: '/assets/images/products/stephen-webster-ray.png',
  prod_georg_jensen_offspring: '/assets/images/products/georg-jensen-offspring.png',
  prod_tiffany_bone: '/assets/images/products/tiffany-bone.png',
  prod_swarovski_millenia: '/assets/images/products/swarovski-millenia.png',
  prod_apm_monaco_jetset: '/assets/images/products/apm-monaco-jetset.png',
  prod_links_of_london_sweetie: '/assets/images/products/links-of-london-sweetie.png',
  prod_fondation_cartier_cuff: '/assets/images/products/fondation-cartier-cuff.png',
  prod_ikepod_hemisphere: '/assets/images/products/ikepod-hemisphere.png',
  prod_tous_bearer: '/assets/images/products/tous-bearer.png',
  prod_missoma_claw: '/assets/images/products/missoma-claw.png',
  prod_tiffany_key: '/assets/images/products/tiffany-key.png',
  prod_vca_magic: '/assets/images/products/vca-magic.png',
  prod_cartier_amulette: '/assets/images/products/cartier-amulette.png',
  prod_chopard_happy: '/assets/images/products/chopard-happy.png',
  prod_bulgari_monete: '/assets/images/products/bulgari-monete.png',
  prod_messika_gatsby: '/assets/images/products/messika-gatsby.png',
  prod_david_yurman_renaissance: '/assets/images/products/david-yurman-renaissance.png',
  prod_roberto_coin_centoventi: '/assets/images/products/roberto-coin-centoventi.png',
  prod_apm_monaco_yummy: '/assets/images/products/apm-monaco-yummy.png',
  prod_swarovski_constella: '/assets/images/products/swarovski-constella.png',
  prod_tiffany_soleste: '/assets/images/products/tiffany-soleste.png',
  prod_gorjana_bali: '/assets/images/products/gorjana-bali.png',
  prod_astley_clarke_biography: '/assets/images/products/astley-clarke-biography.png',
  prod_mejuri_solo: '/assets/images/products/mejuri-solo.png',
  prod_monica_vinader_siren: '/assets/images/products/monica-vinader-siren.png'
};

export function imageForProduct(product) {
  return product.image_url || PRODUCT_IMAGES[product.id]
}

export function imageForCartItem(item) {
  return item.imageUrl || PRODUCT_IMAGES[item.productId]
}
